### ISSUE TITLE
Can't setup on my raspberry pi

### ISSUE THREAD

**Issue by shovington** [krpeacock/google_home_starter#1]
I followed your README, but I can't make it works. 
I start with point 1 and end with point 5 but this is what I get on terminal 

Can you help me?

pi@raspberrypi:~/Desktop/google_home_project/google_home_starter $ npm start(node:3705) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> google_home_controller@1.0.0 start /home/pi/Desktop/google_home_project/google_home_starter
> node app.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/pi/Desktop/google_home_project/google_home_starter/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pi/Desktop/google_home_project/google_home_starter/app.js:137:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

npm ERR! google_home_controller@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google_home_controller@1.0.0 start script.
npm ERR! This is most likely a problem with the google_home_controller package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls google_home_controller
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/google_home_project/google_home_starter
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/google_home_project/google_home_starter/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~/Desktop/google_home_project/google_home_starter $

**Comment by Loris94** [comment]
It seems like you don't have enough permissions to use that port, try with `sudo ~/Desktop/google_home_project/google_home_starter $ npm start ` and it should work. If it doesn't and you'll receive a message saying that the port is already in use try with a different port in the .env file, like port 8080.

**Comment by benplay2** [comment]
I had the same issue, using sudo worked for me, thanks!

`sudo npm start`

**Comment by krpeacock** [comment]
Closing since this seems to have been answered
