### ISSUE TITLE
Error to start npm

### ISSUE THREAD

**Issue by sergey08** [krpeacock/google_home_starter#2]
Hello,

I got follow error message on raspberry Pi. I have not touch file app.js

pi@raspberrypi:~/Proyectos/google_home_starter $ sudo npm start

> google_home_controller@1.0.0 start /home/pi/Proyectos/google_home_starter
> node app.js

/home/pi/Proyectos/google_home_starter/app.js:86
      let date = new Date();
          ^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! google_home_controller@1.0.0 start: `node app.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the google_home_controller@1.0.0 start script.
npm ERR! This is most likely a problem with the google_home_controller package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls google_home_controller
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Proyectos/google_home_starter
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Proyectos/google_home_starter/npm-debug.log
npm ERR! not ok code 0

**Comment by krpeacock** [comment]
As the warnings suggested, it looks like you're using the legacy version of Node.js that comes pre-installed on a Raspberry Pi. You'll need to upgrade Node to run this code. Try following this guide!

http://raspberrypimaker.com/installing-updating-node-js/
